server:
  port: 8080
spring:
  application:
    name: registration-service
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/registration
    username: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
