server:
  port: 8082
spring:
  application:
    name: fraud-service

  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/fraud
    username: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  cloud:
    config:
      enabled: false


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#      true by default:
    fetch-registry: true
    register-with-eureka: true